### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by rri** [gpakosz/.tmux#364]
I kept getting an error like this when I started up a tmux server:

```
/tmp/tmp.e75vj8ySDs.in:23: syntax error
```

Setting `tmux_conf_new_pane_retain_current_path` to `false` (or removing it altogether) in my `.tmux.conf.local` file fixed it.

```
$ tmux -V
tmux next-3.2
```

My version of gpakosz/.tmux is at commit `d6f0f647dd68561ed010f83d8d226383aebfb805`.

On a side note, the comment right above appears to be inaccurate - the default value of `tmux_conf_new_pane_retain_current_path` appears to be `false`, not `true`.

**Comment by gpakosz** [comment]
Hello @rri 👋

Can you please give the `gh-364` branch a try? It sits on an upcoming `optimizations` branch so if you decide to give it a go, please make sure you kill all tmux server and client processes before starting over.

**Comment by rri** [comment]
I confirmed that the error doesn't show up anymore on the new branch, with a fresh restart of the tmux server. Thanks! 👍

**Comment by gpakosz** [comment]
Can you please confirm the `tmux_conf_new_pane_retain_current_path` works for you? When using keyboard bindings and mouse menus. Thanks!

**Comment by rri** [comment]
This turned out to be a bit more complicated than I had anticipated.

The `tmux_conf_new_pane_retain_current_path` configuration does work, validated for both `true` and `false` using keyboard bindings (`C-a` `%`, `C-a` `"`). I didn't try it with the mouse menus (not sure what that is).

There are a couple of other problems that didn't seem to be directly related, but caused confusion, and are likely additional bugs. The second of these might well be a bug in tmux itself.

1. A very similar problem exists with `tmux_conf_new_window_retain_current_path`. Since the default is `false`, this doesn't happen by default, only if you change the setting to `true`.
2. On the `gh-364` branch, tmux never exits cleanly. For comparison, on the `master` branch, exiting the last window of tmux exits the tmux process on the host. On the `gh-364` branch, exiting the last window of tmux still leaves a couple of processes running:

```
Process 1: tmux
Process 2: sh -c trap 'exit 0' TERM; while :; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
```

Killing the server with `tmux kill-server` doesn't help - it doesn't actually terminate these processes, and then gets into a bad state.

```
$ tmux kill-server
$ tmux
server exited unexpectedly
$ tmux
server exited unexpectedly
```

I have to execute a `kill -9` and start over at that point.

**Comment by gpakosz** [comment]
> The `tmux_conf_new_pane_retain_current_path` configuration does work, validated for both true and false using keyboard bindings (C-a %, C-a "). I didn't try it with the mouse menus (not sure what that is).

Thank you. For mouse menus, you need to enable mouse mode with `<prefix>` + `m` then you right click in a pane or on the status line.

BTW when you change your `~/.tmux.conf.local` copy, do it either using `<prefix>` + `e` or make sure you reload the configuration after having edited the file with `<prefix>` + `r`.

> exiting the last window of tmux still leaves a couple of processes running

Yeah good catch. It's caused by the `optimizations` branch on top of which the `gh-364` branch sits. I'll fix that.

**Comment by gpakosz** [comment]
I added a commit to the `optimizations` branch, rebased and force pushed `gh-364` if you want to give it a try. This should ends child processes when the server process quits

**Comment by rri** [comment]
> For mouse menus, you need to enable mouse mode with `<prefix>` + `m` then you right click in a pane or on the status line.

The original fix seems to be still broken for this case.

For reference, I enabled mouse mode in `.tmux.conf.local`, started afresh and tried creating a new pane. With `tmux_conf_new_pane_retain_current_path` set to `false`, everything works fine with the right-click menu. With it set to `true`, the right-click menu doesn't show up; instead, I see a `Syntax error` message in the tmux status pane. **NOTE:** This isn't a problem on the `master` branch; on the `master` branch, despite the initial error and the fact that `tmux_conf_new_pane_retain_current_path` isn't actually honored, the right-click menu does show up correctly.

> I added a commit to the `optimizations` branch, rebased and force pushed `gh-364` if you want to give it a try. This should end child processes when the server process quits

This didn't work as I expected. The processes still persist, and I think the output below shows why:

```
$ ps aux | egrep tmux
riyer    20647  0.2  0.0 130944  4308 ?        Ss   22:44   0:00 tmux
riyer    20798  0.0  0.0 119848  2772 ?        S    22:44   0:00 sh -c trap 'exit 0' TERM; while ps -p 20647 >/dev/null; do nice cut -c3- ~/.tmux.conf | sh -s _uptime; sleep 60; done
```

As you can see the `tmux` process (PID = 20647) is the problematic one that won't go away. So the `while ps -p #{pid}` bit didn't help that part of the problem.

**Comment by gpakosz** [comment]
Indeed. In fact tmux server process not exiting is caused by a recent intentional change in tmux itself. I'll look at options

**Comment by gpakosz** [comment]
Fixed in tmux `master`
```
commit d52ac7d027e40b34e7089addc4f905d03d9c1b16
Author: Nicholas Marriott <nicholas.marriott@gmail.com>
Date:   Fri Jun 12 10:31:12 2020 +0000

    Do not wait on shutdown for commands started with run -b.
```

**Comment by rri** [comment]
> Fixed in tmux `master`

Yes, this seems fixed after I compiled from `HEAD`.

> The original fix seems to be still broken for this case.

This is still broken, but in a different way now. I haven't been able to track down why / how the behavior changed.

Now, I no longer get the `Syntax error` message with right-click, and the mouse menu does show up correctly. However, the `tmux_conf_new_pane_retain_current_path` option is not honored for the Horizontal split; but it works fine for the Vertical split. The keyboard bindings on the other hand continue to work fine for both.

* https://github.com/tmux/tmux/commit/4000052d92395a41cdaa79cfc1df38fc89858cf4
* https://github.com/gpakosz/.tmux/commit/bd39b404df06ed6d00857880457d4b549caaba27

**Comment by gpakosz** [comment]
@rri 👋

tmux fixed what caused the initial problem.
All in all, what remains in the `gh-364` branch I just force pushed is the fix for `tmux_conf_new_pane_retain_current_path`'s default value when there's no `~/.tmux.conf.local`
