### ISSUE TITLE
No status bar in optimizations branch on a mac mini

### ISSUE THREAD

**Issue by mikeage** [gpakosz/.tmux#377]
All of the key binds work, but the status bar shows the default. Based on `git bisect`, this was first broken in 3bfd466b4be31796ed26e23562728695ccf7626d

Adding a return here skips the broken code, but I didn't investigate exactly what isn't working:

```diff
diff --git a/.tmux.conf b/.tmux.conf
index ec46ed0..8c29e78 100644
--- a/.tmux.conf
+++ b/.tmux.conf
@@ -281,6 +281,7 @@ run -b '[ -z "#{window_active}" ] && [ -z "#{version}" ] && tmux set display-tim
 # _battery_info() {
 #   count=0
 #   charge=0
+#   return
 #   case "$_uname_s" in
 #     *Darwin*)
 #       while IFS= read -r line; do
```

**Comment by gpakosz** [comment]
Hello @mikeage 👋

Can you please remove that early `return` statement and while inside tmux run

```
$ cut -c3- ~/.tmux.conf | sh -s _battery_info
```

**Comment by mikeage** [comment]
Empty response (with a return code of 1)

**Comment by gpakosz** [comment]
Oh should have been
```
$ cut -c3- ~/.tmux.conf | sh -sx _battery_info
```

**Comment by mikeage** [comment]
Makes sense ;-)
```
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ printf ''
+ sed -E s///
++ uname -s
+ _uname_s=Darwin
+ command -v pkill
+ _battery_info
+ count=0
+ charge=0
+ case "$_uname_s" in
++ pmset -g batt
++ grep InternalBattery
+ IFS=
+ read -r line
+ '[' x '!=' xtrue ']'
++ printf %s ''
++ grep -qi discharging
++ echo false
+ discharging=false
++ printf %s ''
++ grep -E -o '[0-9]+%'
+ percentage=
```
(exit code 1)

**Comment by mikeage** [comment]
ok, now I see the problem as well. With `$line` empty (because `pmset -g batt | grep 'InternalBattery'` found nothing), the `set -e` exits here.

**Comment by mikeage** [comment]
This fixes it too; not sure if you want something better for `percentage`:
```diff
diff --git a/.tmux.conf b/.tmux.conf
index ec46ed0..336542a 100644
--- a/.tmux.conf
+++ b/.tmux.conf
@@ -287,9 +287,13 @@ run -b '[ -z "#{window_active}" ] && [ -z "#{version}" ] && tmux set display-tim
 #         if [ x"$discharging" != x"true" ]; then
 #           discharging=$(printf '%s' "$line" | grep -qi "discharging" && echo "true" || echo "false")
 #         fi
+#         if [ x"$line" != x ]; then
 #         percentage=$(printf '%s' "$line" | grep -E -o '[0-9]+%')
 #         charge=$(awk -v charge="$charge" -v percentage="${percentage%%%}" 'BEGIN { print charge + percentage / 100 }')
 #         count=$((count + 1))
+#         else
+#         percentage='n/a'
+#         fi
 #       done  << EOF
 # $(pmset -g batt | grep 'InternalBattery')
 # EOF
```

**Comment by gpakosz** [comment]
Do you face the problem on the `master` branch?

**Comment by mikeage** [comment]
Master is fine too. I gave the commit that first broke it in the first comment

**Comment by gpakosz** [comment]
Well yeah. The code in `master` for this part is the same but isn't call from the same place.

Can you please give me the output of
```
$ pmset -g batt
```

You shouldn't even enter the `while IFS= read -r line` loop.

**Comment by mikeage** [comment]
```
$ pmset -g batt
Now drawing from 'AC Power'
$
```
We are entering the loop, but with an empty string for line. I'm not an expert at (ba)sh scripting, but that does look a bit weird to me too. 

Just for fun, I added this:
```
$ git diff
diff --git a/.tmux.conf b/.tmux.conf
index ec46ed0..edd13bf 100644
--- a/.tmux.conf
+++ b/.tmux.conf
@@ -284,6 +284,7 @@ run -b '[ -z "#{window_active}" ] && [ -z "#{version}" ] && tmux set display-tim
 #   case "$_uname_s" in
 #     *Darwin*)
 #       while IFS= read -r line; do
+#         echo "line is |$line|"
 #         if [ x"$discharging" != x"true" ]; then
 #           discharging=$(printf '%s' "$line" | grep -qi "discharging" && echo "true" || echo "false")
 #         fi
```
And it gives me:
```
line is ||
```

**Comment by gpakosz** [comment]
Then `pmset -g batt | grep 'InternalBattery'` gives you an empty line instead of an empty response?

Weird. Did you do something special to your `grep`?

**Comment by mikeage** [comment]
No... it's empty, not a blank line. Here's a full prompt copy/paste
```
  0 mikeage@macmini ~/.tmux {optimizations *$% u=}$ pmset -g batt | grep 'InternalBattery'
  1 mikeage@macmini ~/.tmux {optimizations *$% u=}$
```
I don't understand it at all.
```
  0 mikeage@macmini ~/.tmux {optimizations *$% u=}$ while IFS= read -r line; do echo "Line is |$line|"
done << EOF
$(pmset -g batt | grep 'InternalBattery')
EOF
Line is ||
  0 mikeage@macmini ~/.tmux {optimizations *$% u=}$
```
grep is just /usr/bin/grep, I don't have any $GREP_OPTIONS set...

**Comment by gpakosz** [comment]
What if if you do
```
while IFS= read -r line; do
  echo "Line is "|$line|"
done << EOF
true
EOF
```
?

**Comment by gpakosz** [comment]
Also what is `/bin/sh`?

**Comment by gpakosz** [comment]
Also, what are the line endings for your `~/.tmux.conf` file?

**Comment by mikeage** [comment]
I fixed the quotes in your example, and tried with both `true` and `$(true)` (which I suspect was intended)
```
  0 mikeage@macmini ~/.tmux {optimizations *$% u=}$ while IFS= read -r line; do   echo "Line is |$line|"
done << EOF
true
EOF

Line is |true|
  0 mikeage@macmini ~/.tmux {optimizations *$% u=}$ while IFS= read -r line; do   echo "Line is |$line|"
done << EOF
$(true)
EOF
Line is ||
  0 mikeage@macmini ~/.tmux {optimizations *$% u=}$ ls -altrh /bin/sh
-r-xr-xr-x  1 root  wheel   604K Dec 14  2018 /bin/sh*
  0 mikeage@macmini ~/.tmux {optimizations *$% u=}$ /bin/sh --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Copyright (C) 2007 Free Software Foundation, Inc.
  0 mikeage@macmini ~/.tmux {optimizations *$% u=}$ file .tmux.conf
.tmux.conf: UTF-8 Unicode text, with very long lines
```

**Comment by gpakosz** [comment]
Yeah sorry for the `true` vs `$(true)` typo.
For now I still don't understand why the `while` loop enters

**Comment by gpakosz** [comment]
Well silly me. Of course it's an empty line because of the HEREDOC

**Comment by gpakosz** [comment]
I pushed a fix. Thanks @mikeage for the debugging session 🙏

I'll try to merge this branch soon 🤞

**Comment by mikeage** [comment]
perfect, thank! I don't understand HEREDOCs ;-)
